### PR TITLE
Update linode-blockstorage-csi-driver.yaml

### PR DESCRIPTION
**Pull request by cdeshapriya**
Updated  storage.k8s.io/v1beta1 to storage.k8s.io/v1

### General:

* [ ] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [ ] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

### Pull Request Guidelines:

1. [ ] Does your submission pass tests?
1. [ ] Have you added tests? 
1. [ ] Are you addressing a single feature in this PR? 
1. [ ] Are your commits atomic, addressing one change per commit?
1. [ ] Are you following the conventions of the language? 
1. [ ] Have you saved your large formatting changes for a different PR, so we can focus on your work?
1. [ ] Have you explained your rationale for why this feature is needed? 
1. [ ] Have you linked your PR to an [open issue](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)

### CODE REVIEW

**Comment by srust** [comment]
Thank you for bringing this to our attention! Just created a similar pull request. Either this one needs to be merged or the one I just created at #86. Will reconcile these two PRs and get the change in.

Appreciate keeping an eye out for this change!

**Comment by srust** [comment]
Merging this. Thank you for the contribution!

**Comment by lots0logs** [comment]
@srust Why hasn't a new release been issued that includes this change?

**Comment by srust** [comment]
> @srust Why hasn't a new release been issued that includes this change?

https://github.com/linode/linode-blockstorage-csi-driver/releases/tag/v0.5.1

**Pull request merged**
